name: Build and Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*-SNAPSHOT'

jobs:
  call-env-setup:
    runs-on: ubuntu-latest
    needs: [env-setup]
#    steps:
#      - name: Call Env Setup
#        uses: actions/workflow-runner@v2
#        with:
#          workflow: "env-setup.yml"
#            repository: ${{ github.repository }}
#            ref: ${{ github.sha }}
#            token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run UT
        run: ./gradlew testReleaseUnitTest --parallel