name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 1
      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.4'
      - name: UT
        run: ./gradlew testReleaseUnitTest