name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main

jobs:
  call-env-setup:
    uses: ./.github/workflows/env-setup.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
#  create-gpg-file:
#    uses: ./.github/workflows/create-gpg-file.yml
  check:
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      MY_PROPERTY: ${{ secrets.MY_PROPERTY }}
    needs: [call-env-setup, create-gpg-file]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Print secret
        run: |
          echo ${{env.SIGNING_KEY}}
      - name: Create GPG file
        run: |
          echo ${{env.SIGNING_KEY}} | base64 -d > key.gpg
      - name: key size
        run: du -h key.gpg
      - name: Upload GPG file
        uses: actions/upload-artifact@v2
        with:
          name: key
          path: key.gpg
      - name: Download GPG file
        uses: actions/download-artifact@v2
        with:
          name: key
          path: .
      - name: key size
        run: du -h $(pwd)/key.gpg
      - name: Set file path as environment variable
        run: echo "FILE_PATH=$(pwd)/key.gpg" >> $GITHUB_ENV
      - name: Print file path
        run: |
          echo "File path: ${{ env.FILE_PATH }}"
      - name: Print properties
        run: ./gradlew properties