name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Execute Shell script
        shell: bash
        run: ./sample.sh