name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main


jobs:
  call-env-setup:
    uses: ./.github/workflows/env-setup.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
  create-gpg-file:
    uses: ./.github/workflows/create-gpg-file.yml
  check:
    needs: [call-env-setup, create-gpg-file]
    runs-on: ubuntu-latest
    env:
      path: "${{pwd}}/key.gpg"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
#      - name: Run UT
#        run: ./gradlew testReleaseUnitTest --parallel -s
      - name: Download GPG file
        uses: actions/download-artifact@v2
        with:
          name: key
          path: .
#      - name: Rename downloaded file
#        run: mv key.gpg key.gpg
      - name: Set file path as environment variable
        run: echo "FILE_PATH=$(pwd)/key.gpg" >> $GITHUB_ENV
      - name: Print file path
        run:
          echo "File path: ${{ env.FILE_PATH }}"
      - name: Print properties
        run: ./gradlew properties