name: Build and Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*-SNAPSHOT'

jobs:
  call-env-setup:
    uses: ./.github/workflows/env-setup.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
#    steps:
#      - name: Call Env Setup
#        uses: actions/workflow-runner@v2
#        with:
#          workflow: "env-setup.yml"
#            repository: ${{ github.repository }}
#            ref: ${{ github.sha }}
#            token: ${{ secrets.GITHUB_TOKEN }}
  check:
    needs: [call-env-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run UT
        run: ./gradlew testReleaseUnitTest --parallel