name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main

jobs:
  check_actor:
    runs-on: ubuntu-latest
    steps:
      - name: Check actor
        run: |
          if [[ "${{ github.actor }}" != "WeiWW" ]]; then
            echo "Only required_username can manually trigger this workflow."
            exit 1
          fi
  call-env-setup:
    needs: check_actor
    uses: ./.github/workflows/env-setup.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
  create-gpg-file:
    needs: check_actor
    uses: ./.github/workflows/create-gpg-file.yml
    secrets:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  check:
    needs: [call-env-setup, create-gpg-file]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download GPG file
        uses: actions/download-artifact@v2
        with:
          name: key
          path: .
      - name: key size
        run: du -h $(pwd)/key.gpg
      - name: Set file path as environment variable
        run: echo "FILE_PATH=$(pwd)/key.gpg" >> $GITHUB_ENV
      - name: Print file path
        run: |
          echo "File path: ${{ env.FILE_PATH }}"
      - name: Print properties
        run: ./gradlew properties