name: Build and Test

on:
  workflow_dispatch:
    branches:
      - main
    tags:
        - 'v*.*.*'
  push:
    branches:
      - main


jobs:
  call-env-setup:
    uses: ./.github/workflows/env-setup.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
  create-gpg-file:
    uses: ./.github/workflows/create-gpg-file.yml
  check:
    needs: [call-env-setup, create-gpg-file]
    runs-on: ubuntu-latest
    env:
      MY_PROPERTY: ${{ secrets.MY_PROPERTY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run UT
        run: ./gradlew testReleaseUnitTest --parallel -s
      - name: Download GPG file
        uses: actions/download-artifact@v2
        with:
          name: key
          path: .
      - name: Rename downloaded file
        run: mv key key.gpg
      - name: Check if file exists
        run: |
          if test -f "./key.gpg"; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi