name: Build and Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*-SNAPSHOT'
  workflow_run:
    workflows: ["Env Setup"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run UT
        run: ./gradlew testReleaseUnitTest --parallel