name: Create GPG file

on:
  workflow_call:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo "The secret is ${{ secrets.SIGNING_KEY }}"
      - name: Print secret
        run: echo "The secret is ${{ secrets.MY_PROPERTY }}"
      - name: Create GPG file
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > key.gpg
      - name: key size
        run: du -h key.gpg
      - name: Upload GPG file
        uses: actions/upload-artifact@v2
        with:
          name: key
          path: key.gpg