name: Create GPG file

on:
  workflow_call:

jobs:
  create:
#    env:
#      S_KEY: "${{ secrets.SIGNING_KEY }}"
#      MY_PROPERTY: "${{ secrets.MY_PROPERTY }}"
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        shell: bash
        env:
          S_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "${S_KEY}"
      - name: Print secret
        run: |
          echo "${{ secrets.SIGNING_KEY }}"
      - name: Create GPG file
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > key.gpg
      - name: key size
        run: du -h key.gpg
      - name: Upload GPG file
        uses: actions/upload-artifact@v2
        with:
          name: key
          path: key.gpg